name: Feature request ✨
description: Suggest an idea or ask for a feature that you would like to have
labels: [support, feature-req]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting me know how I can improve this package! ☺️
  - type: dropdown
    attributes:
      label: Stack
      options: 
        - Blade (Default)
        - Vue
        - React
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What does the proposed solution look like?
    validations:
      required: true
